export enum TimeZones {
    'UTC-12:00 - Baker Island Time (BIT)' = -12,
    'UTC-11:00 - Samoa Standard Time (SST), Niue Time (NUT)' = -11,
    'UTC-10:00 - Hawaii-Aleutian Standard Time (HST), Cook Islands Time (CKT)' = -10,
    'UTC-09:00 - Alaska Standard Time (AKST), Gambier Islands Time (GIT)' = -9,
    'UTC-08:00 - Pacific Standard Time (PST), Clipperton Island Standard Time' = -8,
    'UTC-07:00 - Mountain Standard Time (MST), Chihuahua Standard Time (MST)' = -7,
    'UTC-06:00 - Central Standard Time (CST), Galápagos Time (GALT)' = -6,
    'UTC-05:00 - Eastern Standard Time (EST), Colombia Time (COT)' = -5,
    'UTC-04:00 - Atlantic Standard Time (AST), Venezuela Time (VET)' = -4,
    'UTC-03:00 - Argentina Standard Time (ART), French Guiana Time (GFT)' = -3,
    'UTC-02:00 - South Georgia and the South Sandwich Islands Time (GST)' = -2,
    'UTC-01:00 - Azores Standard Time (AZOT), Cape Verde Time (CVT)' = -1,
    'UTC±00:00 - Greenwich Mean Time (GMT), Western European Time (WET)' = 0,
    'UTC+01:00 - Central European Time (CET), West Africa Time (WAT)' = 1,
    'UTC+02:00 - Eastern European Time (EET), Central Africa Time (CAT)' = 2,
    'UTC+03:00 - Moscow Standard Time (MSK), East Africa Time (EAT)' = 3,
    'UTC+04:00 - Gulf Standard Time (GST), Samara Time (SAMT)' = 4,
    'UTC+05:00 - Pakistan Standard Time (PKT), Yekaterinburg Time (YEKT)' = 5,
    'UTC+06:00 - Bangladesh Standard Time (BST), Omsk Time (OMST)' = 6,
    'UTC+07:00 - Indochina Time (ICT), Krasnoyarsk Time (KRAT)' = 7,
    'UTC+08:00 - China Standard Time (CST), Western Australian Standard Time (AWST)' = 8,
    'UTC+09:00 - Japan Standard Time (JST), Korea Standard Time (KST)' = 9,
    'UTC+10:00 - Australian Eastern Standard Time (AEST), Vladivostok Time (VLAT)' = 10,
    'UTC+11:00 - Solomon Islands Time (SBT), Magadan Time (MAGT)' = 11,
}
